# Generated by Django 3.0.6 on 2020-11-28 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_productoimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.Producto'),
        ),
        migrations.CreateModel(
            name='Comerciante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='proveedor',
            name='comerciante',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Comerciante'),
        ),
    ]
