# Generated by Django 3.0.6 on 2020-11-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_pedido_comprobante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='comprobante',
            field=models.CharField(choices=[('Factura', 'Factura'), ('Boleta', 'Boleta')], max_length=7, null=True),
        ),
    ]
